### ISSUE TITLE
Valorant New Act rank yoinker errors out in party+game

### ISSUE THREAD

**Issue by DeadTheAmazing** [isaacKenyon/VALORANT-rank-yoinker#25]
![image_2021-11-02_200634](https://user-images.githubusercontent.com/44987835/139968219-cf194299-062d-4544-a215-7d3aa4cdc6a1.png)
ss of console. After new Act rank yoinker just doesnt work. how to recreate it? launch it.

**Comment by Rayjacker** [comment]
This is very likely due to the new agent Chamber being added, but unactivated until November 16.

**Comment by OwOHamper** [comment]
Use the latest version with python

**Comment by Rayjacker** [comment]
Still doesn't work, using Python 3.10 and the source from https://github.com/isaacKenyon/VALORANT-rank-yoinker/commit/a3bf92308fd5a11b3ed8adc17a0e4dffd40784bb . When checking the [API's agent list](https://valorant-api.com/v1/agents) , there are no mentions of Chamber, so the issue is probably on their end.
![image](https://user-images.githubusercontent.com/77126320/140022334-cd79dd36-59f0-43b0-8d0d-2dfbda3e8475.png)

**Comment by isaacKenyon** [comment]
most apps are experiencing Api problems due to the update. current theory is that a url changed, we'll see what we can do.

**Comment by Rayjacker** [comment]
https://github.com/isaacKenyon/VALORANT-rank-yoinker/commit/f4446fbf83da022722118694ad93ea90f714f0c4 seems to have fixed it. Thank you for the quick fix.
