### ISSUE TITLE
ign

### ISSUE THREAD

**Issue by viperxx01** [isaacKenyon/VALORANT-rank-yoinker#84]
bcoz of riot tos we cant get ign of some players right, im suggesting, save data of last game to json maybe. we can save puuid right? and compare it to current game.  and create new row lastgame.  like this
----------------------------------
Agent         Rank           LastGame
Reyna.        Plat.               Chamber (blue box icon)
Jett.            Gold.             None
blue box means ally.

only a suggestion
Thankss.

**Comment by isaacKenyon** [comment]
This is unlikey to be done as it seems pointless, Tracker.gg offers this functionality.

**Comment by OwOHamper** [comment]
We are planning feature similar to this. Not exactly sure about how we implement it yet. But I am thinking it would print after table message like this: `Already played with Jett 3 days ago (Chamber)`. Or something like that since there are not that many situations where you play again with someone from last game. We are also thinking about sort of marking feature where it would add emoji next to someone name. User could add them manually.

**Comment by isaacKenyon** [comment]
Implemented.
